feat: Improvements for Xiaomi VOCKQJK11LM (#6723)
* feat: switch VOCKQJK11LM to aqaraVoc and aqaraAirQuality modernExtends

Add aqaraAirQuality and aqaraVoc to modernExtends in lib/xiaomi. Switch VOCKQJK11LM to use these new extends.

* feat: switch VOCKQJK11LM to aqaraDisplayUnit modernExtend

* fix: setup batteryVoltage reporting for VOCKQJK11LM

We will switch this to a modernExtend later.

* feat: numeric and export modernExtend should read initial value during configure()

* feat: numeric and export modernExtend should support setting up reporting

* feat: setup reporting for aqaraVoc modernExtend

* fix: use attribute names in new modernExtends

* fix: modernExtend should use attribute.ID so it matches ZHConfigureReportingItem

We pass along some attribute date to of type `ZHConfigureReportingItem` via `setupAttributes()` which expect's it to be **ID** not **id**.

If we do not enforce the capitalizaiton we end up with errors like:

```
Zigbee2MQTT:debug 2023-12-16 21:37:50: Reading for 0x54ef441000684954/1 aqaraOpple [{"attribute":{"id":297,"type":32}}]
Zigbee2MQTT:error 2023-12-16 21:37:50: Failed to configure '0x54ef441000684954', attempt 2 (Error: Cluster 'aqaraOpple' has no attribute 'undefined'
    at Object.getAttribute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/zcl/utils.ts:93:19)
    at Endpoint.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:446:87)
    at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:43:24)
    at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:325:11)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:138:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:117:13))
```

* fix: correct sonoff modernExtends to use ID

* fix: correct xiaomi/aqara modernExtends to use ID

* fix: rename `configureEndpointId` to `endpointID`

This is also used when not setting up reporting by `setupAttributes()` to read the initial value.

* feat: binary modernExtend should support setting up reporting

* Update modernExtend.ts

* add test

* fix

---------

Co-authored-by: Koen Kanters <koenkanters94@gmail.com>